<?php

return [
    '1' => [
        'name' => 'مؤسسة نطاق المتحدة',
        'company_name' => 'مؤسسة نطاق المتحدة',
        'contact_name' => 'فارس (ابوايمن)',
        'contact_mobile_number' => '0501893106',
        'notes' => null,
        'created_at' => '2022-10-22 06:19:56',
        'updated_at' => '2022-11-16 13:16:50',
        'deleted_at' => null,
        'branch_id' => 1,
    ],
    '2' => [
        'name' => 'شركة احكام',
        'company_name' => 'شركة احكام',
        'contact_name' => null,
        'contact_mobile_number' => null,
        'notes' => null,
        'created_at' => '2022-10-22 06:21:49',
        'updated_at' => '2022-10-22 06:24:35',
        'deleted_at' => null,
        'branch_id' => 1,
    ],
    '3' => [
        'name' => 'مؤسسة جودة التشييد',
        'company_name' => 'مؤسسة جودة التشييد',
        'contact_name' => null,
        'contact_mobile_number' => null,
        'notes' => null,
        'created_at' => '2022-10-22 06:22:58',
        'updated_at' => '2022-10-22 06:22:58',
        'deleted_at' => null,
        'branch_id' => 1,
    ],
    '4' => [
        'name' => 'مؤسسة زهرة الديكورات',
        'company_name' => 'مؤسسة زهرة الديكورات',
        'contact_name' => null,
        'contact_mobile_number' => null,
        'notes' => null,
        'created_at' => '2022-10-22 06:23:36',
        'updated_at' => '2022-10-22 06:23:36',
        'deleted_at' => null,
        'branch_id' => 1,
    ],
    '5' => [
        'name' => 'مؤسسة ديم التقنية',
        'company_name' => 'مؤسسة ديم التقنية',
        'contact_name' => null,
        'contact_mobile_number' => null,
        'notes' => null,
        'created_at' => '2022-10-22 06:24:12',
        'updated_at' => '2022-10-22 06:24:12',
        'deleted_at' => null,
        'branch_id' => 1,
    ],
];
