<?php

return [
    '1' => [
        'name' => 'مدير النظام',
        'username' => 'admin',
        'email' => 'admin@alfaseel.com',
        'role'  => 'admin',
        'password'=>'AdMin@P@123987',
        'department_id'=> 7,
        'job_id'=> 9
    ],
    '2' => [
        'name' => 'خليل كساب شراب',
        'username' => 'khalil',
        'email' => 'projects_manager@alfaseel.com',
        'role'  => 'projectManager',
        'department_id'=> 7,
        'job_id'=> 3,
    ],
    '3' => [
        'name' => 'محمد خليل كساب شراب',
        'username' => 'mo__sh',
        'email' => 'mo__sh@hotmail.com',
        'role'  => 'DeputyProjectManager',
        'department_id'=> 7,
        'job_id'=> 4,
    ],
    '4' => [
        'name' => 'عبدالوهاب سيد احمد محمد',
        'username' => 'abdalwahab',
        'email' => 'abdalwahab19995@gmail.com',
        'role'  => 'drillingDepartment',
        'department_id'=>1,
        'job_id'=> 1,
    ],
    '5' => [
        'name' => 'احمد محمد احمد',
        'username' => 'a7md_mursi',
        'email' => 'a7md_mursi@live.com',
        'role'  => 'drillingDepartment',
        'department_id'=> 1,
        'job_id'=> 1,
    ],
    '6' => [
        'name' => 'عماد محمد عبدالوهاب',
        'username' => 'emad5999',
        'email' => 'emad5999@hotmail.com ',
        'role'  => 'emergencyMissionsDepartment',
        'department_id'=> 5,
        'job_id'=> 1,
    ],
    '7' => [
        'name' => 'محمود حسن مطر',
        'username' => 'mahoudmmk',
        'email' => 'mahoudmmk@gmail.com',
        'role'  => 'restablishDepartment',
        'department_id'=> 4,
        'job_id'=> 1,
    ],
    '8' => [
        'name' => 'سيد بشاي محمود علي',
        'username' => 'sayedbeshay',
        'email' => 'sayedbeshay@gmail.com',
        'role'  => 'accounting',
        'department_id'=> 9,
        'job_id'=> 5,
    ],
    '9' => [
        'name' => 'محمد سليم رحمت علي',
        'username' => 'saleem405405',
        'email' => 'saleem405405@gmail.com',
        'role'  => 'stores',
        'department_id'=> 11,
        'job_id'=> 6,
    ],
    '10' => [
        'name' => 'فياض عبدالمعين قصاب',
        'username' => 'engfayyadaif',
        'email' => 'engfayyadaif@gmail.com',
        'role'  => 'paymentClearancesDepartment',
        'department_id'=> 6,
        'job_id'=> 1,
    ],
    '11' => [
        'name' => 'محمد ياسين خان',
        'username' => 'smakash1',
        'email' => 'smakash1@hotmail.com',
        'role'  => 'electricTowersDepartment',
        'department_id'=>3,
        'job_id'=> 1,
    ],
    '12' => [
        'name' => 'عمار محمد يعقوب',
        'username' => 'eng.ammaryaq',
        'email' => 'eng.ammaryaq@gmail.com',
        'role'  => 'paymentClearancesDepartment',
        'department_id'=> 6,
        'job_id'=> 1,
    ],
    '13' => [
        'name' => 'شكيل الرحمن شيخ',
        'username' => 'sksakil007',
        'email' => 'sksakil007@gmail.com',
        'role'  => 'electricTowersDepartment',
        'department_id'=> 3,
        'job_id'=> 1,
    ],
    '14' => [
        'name' => 'اسامة احمد محمد همام',
        'username' => 'almo7asb',
        'email' => 'almo7asb@outlook.com',
        'role'  => 'accounting',
        'department_id'=> 9,
        'job_id'=> 5,
    ],
    '15' => [
        'name' => 'عبدالله عبيد بخيت الصاعدي',
        'username' => 'alharbyabd38',
        'email' => 'alharbyabd38@gmail.com',
        'role'  => 'stores',
        'department_id'=> 11,
        'job_id'=> 6,
    ],
    '16' => [
        'name' => 'مبصر احمد خطيب',
        'username' => 'muba.star007',
        'email' => 'muba.star007@gmail.com',
        'role'  => 'stores',
        'department_id'=> 11,
        'job_id'=> 6,
    ],
    '17' => [
        'name' => 'احمد ممدوح عبدالفتاح سعيد',
        'username' => 'aalghonaime',
        'email' => 'aalghonaime@gmail.com',
        'role'  => 'management',
        'department_id'=> 14,
        'job_id'=> 8,
    ],
    '18' => [
        'name' => 'عبدالكريم احمد يوسف',
        'username' => '9abd611',
        'email' => '9abd611@gmail.com',
        'role'  => 'electricityDepartment',
        'department_id'=> 14,
        'job_id'=> 2,
    ]
];